<Project Sdk="Fahrenheit.Sdk/1.0.0-alpha11">
    <PropertyGroup>
        <AssemblyName>playable-seymour</AssemblyName>
        <AssemblyTitle>Playable Seymour</AssemblyTitle>
        <Product>Playable Seymour</Product>
        <Description>A FINAL FANTASY X HD Remaster mod to make Seymour his own, standalone character.</Description>
        <Version>1.0.0-alpha</Version>
        <Authors>cxldalyy</Authors>
        <RepositoryUrl>https://github.com/cxldalyy/playable-seymour-mod</RepositoryUrl>
        <FhManifestFlags>SEPARATE_SAVES</FhManifestFlags>
    </PropertyGroup>
</Project>
